#include "Tags/GameSettingsTags.h"


// Game Audio
GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_AUDIO_MASTER, "GameSettings.Audio.Master", "");

GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_AUDIO_USERINTERFACE, "GameSettings.Audio.UserInterface", "");
GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_AUDIO_MUSIC, "GameSettings.Audio.Music", "");
GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_AUDIO_SOUNDEFFECTS, "GameSettings.Audio.SoundEffects", "");
GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_AUDIO_ENEMYSOUNDEFFECTS, "GameSettings.Audio.EnemySoundEffects", "");
GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_AUDIO_FOOTSTEPS, "GameSettings.Audio.Footsteps", "");
GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_AUDIO_VOICES, "GameSettings.Audio.Voices", "");
GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_AUDIO_AMBIENT, "GameSettings.Audio.Ambient", "");


// Game Options
GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_GAMEOPTION_TOOLTIP_ALWAYSONCURSOR, "GameSettings.GameOption.Tooltip.AlwaysOnCursor", "");

GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_GAMEOPTION_MOUSE_LOCKCURSORTOSCREEN, "GameSettings.GameOption.Mouse.LockCursorOnScreen", "");

GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_GAMEOPTION_BARS_SHOWVALUES, "GameSettings.GameOption.Bars.ShowValues", "");
GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_GAMEOPTION_BARS_SHOWPERCENTAGEVALUES, "GameSettings.GameOption.Bars.ShowPercentageValues", "");
GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_GAMEOPTION_BARS_ENABLEANIMATIONS, "GameSettings.GameOption.Bars.EnableAnimations", "");

GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_GAMEOPTION_ABILITIES_SHOWINDICATORS, "GameSettings.GameOption.Abilities.ShowIndicators", "");
GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_GAMEOPTION_ABILITIES_SHOWCOOLDOWNVALUES, "GameSettings.GameOption.Abilities.ShowCooldownValues", "");
GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_GAMEOPTION_ABILITIES_SHOWMANACOSTVALUES, "GameSettings.GameOption.Abilities.ShowManaCostValues", "");

GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_GAMEOPTION_FLOATINGTEXT_ENABLE, "GameSettings.GameOption.FloatingText.Enable", "");
GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_GAMEOPTION_FLOATINGTEXT_SHOWDAMAGE, "GameSettings.GameOption.FloatingText.ShowDamage", "");
GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_GAMEOPTION_FLOATINGTEXT_SHOWHEALING, "GameSettings.GameOption.FloatingText.ShowHealing", "");
GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_GAMEOPTION_FLOATINGTEXT_SHOWCROWDCONTROL, "GameSettings.GameOption.FloatingText.ShowCrowdControl", "");
GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_GAMEOPTION_FLOATINGTEXT_SHOWCONDITIONS, "GameSettings.GameOption.FloatingText.ShowConditions", "");
GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_GAMEOPTION_FLOATINGTEXT_SHOWIMMUNITIES, "GameSettings.GameOption.FloatingText.ShowImmunities", "");
GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_GAMEOPTION_FLOATINGTEXT_SHOWLOWLIFE, "GameSettings.GameOption.FloatingText.ShowLowLife", "");
GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_GAMEOPTION_FLOATINGTEXT_SHOWLOWRESOURCE, "GameSettings.GameOption.FloatingText.ShowLowResource", "");
GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_GAMEOPTION_FLOATINGTEXT_SHOWEXPERIENCE, "GameSettings.GameOption.FloatingText.ShowExperience", "");
GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_GAMEOPTION_FLOATINGTEXT_SHOWLEVELUP, "GameSettings.GameOption.FloatingText.ShowLevelUp", "");

GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_GAMEOPTION_OVERUNITS_SHOWNAME, "GameSettings.GameOption.OverUnits.ShowName", "");
GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_GAMEOPTION_OVERUNITS_SHOWLIFEBAR, "GameSettings.GameOption.OverUnits.ShowLifeBar", "");
GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_GAMEOPTION_OVERUNITS_SHOWLIFEBARSCALE, "GameSettings.GameOption.OverUnits.ShowLifeBarScale", "");

// Game Values
GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_GAMEVALUE_MOUSE_MOUSESENSITIVITY, "GameSettings.GameValue.Mouse.Sensitivity", "");

GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_GAMEVALUE_CAMERA_SCROLLINGSPEED, "GameSettings.GameValue.Camera.ScrollingSpeed", "");
GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_GAMEVALUE_CAMERA_ROTATIONSPEED, "GameSettings.GameValue.Camera.RotationSpeed", "");
GAMESETTINGS_API GAMESETTINGS_DEFINE_GAMEPLAY_TAG(TAG_GAMESETTINGS_GAMEVALUE_CAMERA_ZOOMSPEED, "GameSettings.GameValue.Camera.ZoomSpeed", "");
